- can-reflect.md
- reflections/call/call.js
- reflections/get-set/get-set.js
- reflections/observe/observe.js
- reflections/shape/shape.js
- reflections/type/type.js
These don't yet have in-depth descriptions or code examples, but do have full coverage.
> Add docs for all modules and functions in reflect

- reflections/shape/shape-test.js
- reflections/type/type-test.js
- test.html
> IE support

- reflections/type/type-test.js
- reflections/type/type.js
> check for non-enumerable on constructor prototype

- reflections/type/type-test.js
- reflections/type/type.js
> check if the function has an unusual proto chain

- package.json
- reflections/get-set/get-set.js
- reflections/shape/shape-test.js
- reflections/shape/shape.js
> NOT READY: adds .serialize and .toPlain 

- reflections/get-set/get-set-test.js
- reflections/get-set/get-set.js
- reflections/type/type.js
> symbols should always be set and avoid the setKeyValue symbol

- reflections/get-set/get-set.js
> slightly faster branching

- package.json
Travis publishing means we don't need these.
> Remove unneeded scripts

- types/map.js
- types/set.js
Typeof returns "undefined" as a string.
> typeof returns string

- package.json
- reflections/observe/observe-test.js
- reflections/observe/observe.js
passes along multiple arguments correctly
> support for queues

- can-reflect.md
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/chasenlehara/e754bc6b6e8cdda69814372a33dfac80**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.
> Update docs with new @parent & @collection

- reflections/get-set/get-set.js
- reflections/type/type.js
Unless they aren’t meant to be public API, I think these are how they’re supposed to be documented.
Part of https://github.com/canjs/canjs/issues/3660
> Add @parent to alias functions

- package.json
- reflections/observe/observe.js
- reflections/shape/shape-test.js
- reflections/shape/shape.js
Closes https://github.com/canjs/can-reflect/issues/70 and helps prepare can-reflect for CanJS 4.0
Also added onPatches/offPatches because I was on a roll.
> Reflections for defining on prototype and listening on other listeners

- reflections/observe/observe-test.js
- reflections/observe/observe.js
> Base implementation of new symbols

- reflections/observe/observe-test.js
- reflections/observe/observe.js
> Prevent getChangesDependecyRecord to throw

- reflections/get-name/get-name.js
> Improve canReflect.getName docs

- can-reflect.md
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/christopherjbaker/49b7e985b37032902d68a17dd2daa070**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.
> Cleanup markdown sample code

- reflections/observe/observe.js
- reflections/shape/schema/schema-test.js
- reflections/shape/schema/schema.js
- reflections/shape/shape-test.js
- reflections/shape/shape.js
> documented serialize and unwrap, adding getIdentity, cloneSortKey, getSchema

- reflections/shape/shape-test.js
> tests that objects w/o hasOwnProperty work with .size

- reflections/get-set/get-set-test.js
- reflections/get-set/get-set.js
- reflections/type/type-test.js
- reflections/type/type.js
fixes #112
Fixed splice by argument checking
> splice fix training 

- reflections/shape/shape-test.js
- reflections/shape/shape.js
> handle primitive return types from serialize 

- package.json
- reflections/type/type-test.js
- reflections/type/type.js
closes https://github.com/canjs/can-reflect/issues/153
> using canSymbol polyfill instead of another polyfill

- package.json
- reflections/call/call-test.js
- reflections/get-set/get-set-test.js
- reflections/observe/observe-test.js
- reflections/shape/schema/schema-test.js
- reflections/shape/shape-test.js
- reflections/type/type-test.js
- types/map-test.js
- types/set-test.js
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/cherifGsoul/e82fd3546da2c3bdabe4b4b9c918d361**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.
> Landscaper: QUnit2 upgrade
