reflections/shape/shape-test.js
reflections/shape/shape.js

Though part of my efforts on [can-define] involve implementing `Symbol.iterator` for DefineList, having iterators is not the expected behavior for many list-likes, so this is a small fix to ensure that `list[Symbol.iterator]` isn't expected to exist.

Support ListLikes that don't implement @@iterator

---

reflections/type/type-test.js
reflections/type/type.js

Object types can define `@@can.isMapLike`, `@@can.isValueLike`, and `@@can.isListLike` as symbols, and these should take precedence over inference methods, like whether `@@can.getValue` exists.

Check for existence of is[Map/List/Value]Like symbols during type tests

---

reflections/shape/shape-test.js
reflections/shape/shape.js

This caches the getters and setters on [update|assign]Map[Deep|].

cache get and set value methods

---

package.json

It’s not used and it breaks Browserify usage.

Remove cssify configuration

---

reflections/get-set/get-set-test.js

This is a part of https://github.com/canjs/canjs/issues/3276.

Fix QUnit.equal usage

---

reflections/shape/shape-test.js
reflections/shape/shape.js
reflections/type/type-test.js
reflections/type/type.js

Made a `isBuiltIn` function and use it to just return built-in values (besides POJOs) when `serializer` is ran.
This will prevent things like dates or regex from returning an empty object instead of their serialized value.
for https://github.com/canjs/can-define/issues/237

Made isBuiltIn and return non-POJO built-ins on serialize

---

can-reflect-test_helpers.js
reflections/shape/shape-test.js
reflections/type/type-test.js
reflections/type/type.js

IE 9/10 do not support Map/Set and even using `if(Map) {}` will cause an error.
Switched to using `typeof Map !== 'undefined`
In addition in IE 11 Map/Set do not properly have `toString` defined and will return `[object Object]` rather than `[object Set]` or `[object Map]` so functions were made in a test helpers module to check for these cases.
For #38

Added helpers to see is map/set are implemented and properly supported

---

reflections/type/type-test.js
reflections/type/type.js

Prior to this fix:
```js
canReflect.isObservableLike([]) //undefined
canReflect.isObservableLike({}) //undefined
canReflect.isObservableLike(null) //false
```
Expected/fixed behavior:
```
canReflect.isObservableLike([]) //false
canReflect.isObservableLike({}) //false
canReflect.isObservableLike(null) //false
```

Fixed observableLike to default to returning false

---

package.json
reflections/observe/observe.js
reflections/shape/shape-test.js
reflections/shape/shape.js

This adds:
- defineInstanceKey - define a key behavior on instances of a type
- onInstanceBoundChange - listen to when instances of this type are bound or unbound
- onInstanceBatches - listen to the patches events of all instances of this type
- onPatches - listen to patch events on this type

onInstanceBoundChange, defineInstanceKey, onInstanceBatches, onPatches

---

reflections/observe/observe.js

From the generated docs.
Closes #82 and #84

Hide getWhatIChange and getChangesDependencyRecord

---

reflections/observe/observe.js

`onInstancePatches` was being linked by `can-event-queue/type/type` but since the method was not document the link was broken.
It works now.

Add onInstancePatches and offInstancePatches

---

package.json
reflections/shape/shape-test.js
reflections/shape/shape.js

This handles cycles in serialize() by using the same technique that
unwrap() uses to handle cycles. But since in this case we don't have a
MapType in which to work, we are just going to use Maps instead.
Closes #96

Handle cycles in serialize()

---

package.json
reflections/shape/shape.js

This updates the cycles implementation to not depend on can-cid for its
Map polyfill. Instead inline a simple version.
Closes #98

Remove dependency on can-cid

---

reflections/observe/observe.js

syntax highlighting training 

---

reflections/shape/shape-test.js
reflections/shape/shape.js

serialize() throws when it encounters a circular reference. However
because a global variable was being used, that global variable had
preserved state that would be reused in all future calls to serialize.
This caused a problem, particular with lists, which might be serialized
multiple times, being mutated in between serialization. In which case
they would always return the same (incorrect) value.
I fixed this by refactoring and making the global state a little more
explicit / easier to read, and providing a method `.end()` that does the
necessary clean up.
This will fix the failing canjs/canjs tests.

Reset global state when throwing b/c of circular refs

---

can-reflect.js
reflections/get-name/get-name.js

This fixes the first part of https://github.com/canjs/canjs/issues/4170 ```Debug code is left in production builds```

fix debug/dev code for webpack

---

reflections/shape/schema/schema-test.js
reflections/shape/schema/schema.js

`canReflect.getSchema( undefined )` now returns `undefined`
Fixes https://github.com/canjs/can-diff/issues/2

Make getSchema return undefined when passed undefined

---

.travis.yml
test-saucelabs.js

There is an issue with Safari not correctly using proxy servers when
using `localhost`
(https://support.saucelabs.com/hc/en-us/articles/115009908527
), which breaks Sauce labs tests that need SauceConnect. This change
maps localhost to http://canjs.test and updates the saucelabs script to
use this.
closes https://github.com/canjs/can-reflect/issues/128.

changing host for test-saucelabs script

---

reflections/shape/shape.js

This fixes the update and updateDeep docs. It does two things:
* Fixes the examples which were shown using `assign` and `assignDeep`.
* Explains that properties from `target` will be removed if not
available on `source`.
Closes #141

Fixes the update/updateDeep docs

---

reflections/shape/shape-test.js
reflections/shape/shape.js

for #143 
essentially `assignDeep()` on a list was doing an assign on the list, but was doing updates on all items within the list.
This PR makes it so it does assigns recursively down.
It's possible people were expecting properties to be removed.  This will break those apps.

assign deep should work recursively

---

package.json
reflections/get-set/get-set-test.js
reflections/shape/shape.js
reflections/type/type-test.js
reflections/type/type.js
types/map.js
types/set.js

I need a hand resolving these issues so I don't blow up the code.
```js
reflections/shape/shape.js: line 150, col 12, 'createSerializeMap' was used before it was defined.
reflections/shape/shape.js: line 304, col 21, If a strict mode function is executed using function invocation, its 'this' value will be undefined.
reflections/shape/shape.js: line 308, col 3, If a strict mode function is executed using function invocation, its 'this' value will be undefined.
reflections/shape/shape.js: line 329, col 6, If a strict mode function is executed using function invocation, its 'this' value will be undefined.
reflections/type/type.js: line 400, col 10, 'isPlainObject' was used before it was defined.
types/map.js: line 9, col 3, If a strict mode function is executed using function invocation, its …
```

Fixes #139. Adds other directories to jshint

---

reflections/type/type-test.js

This makes it so the test will work in canjs/canjs.

not using relative module path with steal-clone

---

reflections/shape/schema/schema-test.js
reflections/shape/schema/schema.js

If dates aren't treated as primitive-ish, then they become empty objects in cloneKeySort(), which is undesirable.  This PR treats dates specially (and only dates, as they are likely to be used in queries whereas other special types like RegExp and Set are less likely to be).
Closes #163

Special case dates when sorting keys

---

reflections/type/type-test.js
reflections/type/type.js

this will help can-component and other view libraries identify Scope objects even if they are from a different CanJS version or not CanJS at all.

Add isScopeLike() type reflection
